version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    groups:
      standard:
        patterns:
          - "standard"
      alt:
        patterns:
          - "*"