steps:
  # Pull docker image
  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$_IMAGE_PROJECT/ringesentralen-frontend:latest

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
          'beta',
          'run',
          'deploy',
          'ringesentralen-prod-frontend',
          '--image', 'gcr.io/$_IMAGE_PROJECT/ringesentralen-frontend:latest',
          '--allow-unauthenticated',
          '--platform=managed',
          '--region=europe-north1'
      ]