steps:
  # Create docker image
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --build-arg HYPERSYSURL=$_HYPERSYSURL
      - --build-arg AMPLITUDE_API_KEY=$_AMPLITUDE_API_KEY
      - --build-arg SENTRYURL=$_SENTRYURL
      - --build-arg IS_PRODUCTION=$_IS_PRODUCTION
      - --build-arg SYSTEMBRUKER=$$SYSTEMBRUKER
      - --build-arg SYSTEMBRUKERPASSORD=$$SYSTEMBRUKERPASSORD
      - --build-arg FRONTENDTOKENKEY=$$FRONTENDTOKENKEY
      - --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_ID=$$NEXT_PUBLIC_RECAPTCHA_SITE_ID
      - --build-arg RECAPTCHA_SECRET=$$RECAPTCHA_SECRET
      - --build-arg TWILIO_TWIML_APP_SID=$$TWILIOTWIMLAPPSID
      - --build-arg TWILIO_ACCOUNT_SID=$$TWILIOACCOUNTSID
      - --build-arg TWILIO_AUTH_TOKEN=$$TWILIOAUTHTOKEN
      - --build-arg TWILIO_CALLER_ID=$$TWILIOCALLERID
      - --build-arg TWILIO_SMS_ID=$$TWILIOSMSID
      - --build-arg TWILIO_SMS_NUMMER=$$TWILIOSMSNUMMER
      - --build-arg TWILIO_API_KEY=$$TWILIOAPIKEY
      - --build-arg TWILIO_API_SECRET=$$TWILIOAPISECRET
      - --build-arg COOKIE_SECRET=$$COOKIESECRET
      - --build-arg ENCRYPTION_KEY=$$ENCRYPTION_KEY
      - --cache=true
      - --destination=gcr.io/$PROJECT_ID/ringesentralen-frontend
    secretEnv: ['SYSTEMBRUKER', 'SYSTEMBRUKERPASSORD', 'FRONTENDTOKENKEY', 'NEXT_PUBLIC_RECAPTCHA_SITE_ID', 'RECAPTCHA_SECRET', 'TWILIOTWIMLAPPSID', 'TWILIOACCOUNTSID', 'TWILIOAUTHTOKEN', 'TWILIOCALLERID', 'TWILIOSMSID', 'TWILIOSMSNUMMER', 'TWILIOAPIKEY', 'TWILIOAPISECRET', 'COOKIESECRET', 'ENCRYPTION_KEY']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'ringesentralen-frontend',
        '--image', 'gcr.io/$PROJECT_ID/ringesentralen-frontend',
        '--allow-unauthenticated',
        '--platform=managed',
        '--region=europe-north1'
      ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/frontendTokenKey/versions/latest
      env: 'FRONTENDTOKENKEY'
    - versionName: projects/$PROJECT_ID/secrets/frontendSystembruker/versions/latest
      env: 'SYSTEMBRUKER'
    - versionName: projects/$PROJECT_ID/secrets/frontendSystembrukerPassord/versions/latest
      env: 'SYSTEMBRUKERPASSORD'
    - versionName: projects/$PROJECT_ID/secrets/TWILIO_TWIML_APP_SID/versions/latest
      env: 'TWILIOTWIMLAPPSID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_RECAPTCHA_SITE_ID/versions/latest
      env: 'NEXT_PUBLIC_RECAPTCHA_SITE_ID'
    - versionName: projects/$PROJECT_ID/secrets/RECAPTCHA_SECRET/versions/latest
      env: 'RECAPTCHA_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/TWILIO_ACCOUNT_SID/versions/latest
      env: 'TWILIOACCOUNTSID'
    - versionName: projects/$PROJECT_ID/secrets/TWILIO_AUTH_TOKEN/versions/latest
      env: 'TWILIOAUTHTOKEN'
    - versionName: projects/$PROJECT_ID/secrets/TWILIO_CALLER_ID/versions/latest
      env: 'TWILIOCALLERID'
    - versionName: projects/$PROJECT_ID/secrets/TWILIO_SMS_ID/versions/latest
      env: 'TWILIOSMSID'
    - versionName: projects/$PROJECT_ID/secrets/TWILIO_SMS_NUMMER/versions/latest
      env: 'TWILIOSMSNUMMER'
    - versionName: projects/$PROJECT_ID/secrets/TWILIO_API_KEY/versions/latest
      env: 'TWILIOAPIKEY'
    - versionName: projects/$PROJECT_ID/secrets/TWILIO_API_SECRET/versions/latest
      env: 'TWILIOAPISECRET'
    - versionName: projects/$PROJECT_ID/secrets/COOKIE_SECRET/versions/latest
      env: 'COOKIESECRET'
    - versionName: projects/$PROJECT_ID/secrets/encryptionKey/versions/latest
      env: 'ENCRYPTION_KEY'
