FROM node:14-alpine AS base
ARG HYPERSYSURL
ARG SENTRYURL
ARG IS_PRODUCTION
ARG SYSTEMBRUKER
ARG SYSTEMBRUKERPASSORD
ARG FRONTENDTOKENKEY
ARG TWILIO_TWIML_APP_SID
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_CALLER_ID
ARG TWILIO_API_KEY
ARG TWILIO_API_SECRET
ARG COOKIE_SECRET
WORKDIR /base
COPY package*.json ./
RUN npm install
COPY . .

FROM base AS build
ARG HYPERSYSURL
ARG SENTRYURL
ARG IS_PRODUCTION
ARG SYSTEMBRUKER
ARG SYSTEMBRUKERPASSORD
ARG FRONTENDTOKENKEY
ARG TWILIO_TWIML_APP_SID
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_CALLER_ID
ARG TWILIO_API_KEY
ARG TWILIO_API_SECRET
ARG COOKIE_SECRET
ENV NEXT_PUBLIC_HYPERSYS_BASE_URL=$HYPERSYSURL
ENV NEXT_PUBLIC_SENTRY_DSN=$SENTRYURL
ENV NEXT_PUBLIC_IS_PRODUCTION=$IS_PRODUCTION
ENV NODE_ENV=production
WORKDIR /build
COPY --from=base /base ./
RUN npm run build

FROM node:14-alpine AS production
ENV NODE_ENV=production
ARG SYSTEMBRUKER
ARG SYSTEMBRUKERPASSORD
ARG FRONTENDTOKENKEY
ARG TWILIO_TWIML_APP_SID
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_CALLER_ID
ARG TWILIO_API_KEY
ARG TWILIO_API_SECRET
ARG COOKIE_SECRET
ENV API_AUTH_KEY=${FRONTENDTOKENKEY}
ENV SERVICEBRUKER_BRUKERNAVN=${SYSTEMBRUKER}
ENV SERVICEBRUKER_PASSORD=${SYSTEMBRUKERPASSORD}
ENV TWILIO_TWIML_APP_SID=${TWILIO_TWIML_APP_SID}
ENV TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
ENV TWILIO_CALLER_ID=${TWILIO_CALLER_ID}
ENV TWILIO_API_KEY=${TWILIO_API_KEY}
ENV TWILIO_API_SECRET=${TWILIO_API_SECRET}
ENV COOKIE_SECRET=${COOKIE_SECRET}
WORKDIR /app
COPY --from=build /build/package*.json ./
COPY --from=build /build/.next ./.next
COPY --from=build /build/public ./public
RUN npm install next

EXPOSE 3000
CMD npm run start