on:
  push:
    branches:
      - main
name: Test and Deploy on release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm install
    - run: npm test
    - run: vc --prod --confirm --token ${VERCEL_TOKEN}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
